package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/Galdoba/devtools/configmanager"
	"github.com/Galdoba/devtools/gpath"
)

const (
	appName = "relay"
	version = "v 0.2.1"
)

type configuration struct {
	app      string
	path     string
	isCustom bool
	MsgStore string `yaml:"Message Storage Directory"` //
	Cycle    int    `yaml:"Restart Cycle"`             //Restart loop for relay (seconds)
	Log      string `yaml:"Log Location"`              //whrere log file is kept
	LogLevel int    `yaml:"Logger Level"`              //write messages of this level and above
}

type ConfigFile interface {
	Save() error
	SaveAs(string) error
	SetDefault() error
	Path() string
	AppName() string
	IsCustom() bool
}

type Config interface {
	ConfigFile
	MessageStorageDirectory() string
	RestartCycle() int
	LogLocation() string
	LoggerLevel() int
	SetMessageStorageDirectory(string)
	SetRestartCycle(int)
	SetLogLocation(string)
	SetLoggerLevel(int)
}

// //////////NEW-SAVE-LOAD////////////
// New - autogenerated constructor of config file
func New() Config {
	cfg := configuration{}
	cfg.path = configmanager.DefaultConfigDir(appName) + "config.yaml"
	cfg.app = appName
	return &cfg
}

// Save - autogenerated constructor of config file
func (cfg *configuration) Save() error {
	data := []byte(header())
	bt, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("can't marshal config: %v", err.Error())
	}
	if err := os.MkdirAll(filepath.Dir(cfg.path), 0777); err != nil {
		return fmt.Errorf("can't create directory")
	}
	f, err := os.OpenFile(cfg.path, os.O_CREATE|os.O_WRONLY, 0777)
	if err != nil {
		return fmt.Errorf("can't open file: %v", err.Error())
	}
	defer f.Close()
	f.Truncate(0)
	data = append(data, bt...)
	_, err = f.Write(data)
	if err != nil {
		return fmt.Errorf("can't write file: %v", err.Error())
	}
	return nil
}

// SaveAs - autogenerated saver of alternative config file
func (cfg *configuration) SaveAs(path string) error {
	cfg.path = path
	cfg.isCustom = true
	return cfg.Save()
}

// Load - Load default config
func Load() (Config, error) {
	path := stdConfigPath()
	cfg, err := loadConfig(path)
	if err != nil {
		return nil, fmt.Errorf("can't load default config: %v", err.Error())
	}
	cfg.isCustom = true
	return cfg, nil
}

// LoadCustom - Loader custom config
func LoadCustom(path string) (Config, error) {
	cfg, err := loadConfig(path)
	if err != nil {
		return nil, fmt.Errorf("can't load custom config: %v", err.Error())
	}
	cfg.isCustom = true
	return cfg, nil
}

// loadConfig - autogenerated loader config file
func loadConfig(path string) (*configuration, error) {
	bt, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("%v", err.Error())
	}
	cfg := &configuration{}
	cfg.path = path
	cfg.app = appName
	err = yaml.Unmarshal(bt, cfg)
	if err != nil {
		return nil, fmt.Errorf("%v", err.Error())
	}
	return cfg, nil
}

////////////HELPERS////////////

// Path - return filepath of current config
func (cfg *configuration) Path() string {
	return cfg.path
}

// IsCustom - return true if config is custom
func (cfg *configuration) IsCustom() bool {
	return cfg.isCustom
}

// AppName - return true if config is custom
func (cfg *configuration) AppName() string {
	return cfg.app
}

// DefaultPath - return default path of current config
func DefaultPath() string {
	return configmanager.DefaultConfigDir(appName) + "config.yaml"
}
func stdConfigDir() string {
	path, err := os.UserHomeDir()
	if err != nil {
		panic(err.Error())
	}
	sep := string(filepath.Separator)
	path += sep
	return path + ".config" + sep + appName + sep
}

func stdConfigPath() string {
	return stdConfigDir() + "config.yaml"
}

////////////GETTERS////////////

// MessageStorageDirectory - autogenerated getter for 'Message Storage Directory' option
func (cfg *configuration) MessageStorageDirectory() string {
	return cfg.MsgStore
}

// RestartCycle - autogenerated getter for 'Restart Cycle' option
// Restart loop for relay (seconds)
func (cfg *configuration) RestartCycle() int {
	return cfg.Cycle
}

// LogLocation - autogenerated getter for 'Log Location' option
// whrere log file is kept
func (cfg *configuration) LogLocation() string {
	return cfg.Log
}

// LoggerLevel - autogenerated getter for 'Logger Level' option
// write messages of this level and above
func (cfg *configuration) LoggerLevel() int {
	return cfg.LogLevel
}

////////////SETTERS////////////

// SetMessageStorageDirectory - autogenerated setter for 'Message Storage Directory' option
func (cfg *configuration) SetMessageStorageDirectory(msgstore string) {
	cfg.MsgStore = msgstore
}

// SetRestartCycle - autogenerated setter for 'Restart Cycle' option
func (cfg *configuration) SetRestartCycle(cycle int) {
	cfg.Cycle = cycle
}

// SetLogLocation - autogenerated setter for 'Log Location' option
func (cfg *configuration) SetLogLocation(log string) {
	cfg.Log = log
}

// SetLoggerLevel - autogenerated setter for 'Logger Level' option
func (cfg *configuration) SetLoggerLevel(loglevel int) {
	cfg.LogLevel = loglevel
}

func (cfg *configuration) SetDefault() error {
	cfg.SetLogLocation(gpath.StdLogPath(appName))
	return cfg.Save()
}

func header() string {
	hdr := ""
	hdr += `################################################################################` + "\n"
	hdr += `#                 This file was generated by configbuilder app                 #` + "\n"
	hdr += `#                     Check formatting rules before editing                    #` + "\n"
	hdr += `#                 https://docs.fileformat.com/programming/yaml/                #` + "\n"
	hdr += `################################################################################` + "\n"
	hdr += `# builder version  : v 0.2.1` + "\n"
	hdr += `# expected location: C:\Users\Admin\.config\relay\config.yaml` + "\n"
	hdr += `# app name         : relay` + "\n"
	hdr += `` + "\n"
	return hdr
}
